hms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('accounts/', include('allauth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/urls.py
from django.urls import path
from .views import RoomListView, BookingListView, RoomDetailView, CancelBookingView

app_name = 'hotel'

urlpatterns = [
    path('', RoomListView, name='RoomListView'),
    path('rooms/booking_list/', BookingListView.as_view(), name='BookingListView'),
    path('rooms/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('booking/cancel/<pk>', CancelBookingView.as_view(),
         name='CancelBookingView')

]

hotel/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse_lazy

# Create your models here.


class Room(models.Model):
    ROOM_CATEGORIES = (
        ('YAC', 'AC'),
        ('NAC', 'NON-AC'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
    )
    number = models.IntegerField()
    category = models.CharField(max_length=3, choices=ROOM_CATEGORIES)
    beds = models.IntegerField()
    capacity = models.IntegerField()

    def __str__(self):
        return f'{self.number}. {dict(self.ROOM_CATEGORIES)[self.category]} Beds = {self.beds} People = {self.capacity}'


class Booking(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in = models.DateTimeField()
    check_out = models.DateTimeField()

    def __str__(self):
        return f'From = {self.check_in.strftime("%d-%b-%Y %H:%M")} To = {self.check_out.strftime("%d-%b-%Y %H:%M")}'

    def get_room_category(self):
        room_categories = dict(self.room.ROOM_CATEGORIES)
        room_category = room_categories.get(self.room.category)
        return room_category

    def get_cancel_booking_url(self):
        return reverse_lazy('hotel:CancelBookingView', args=[self.pk, ])

hotel/forms.py
from django import forms
from .models import Room, Booking

class AvailabilityForm(forms.Form):
    check_in = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])
    check_out = forms.DateTimeField(
        required=True, input_formats=["%Y-%m-%dT%H:%M", ])

hotel/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect
from django.views.generic import ListView, FormView, View, DeleteView
from django.urls import reverse, reverse_lazy
from .models import Room, Booking
from .forms import AvailabilityForm
from hotel.booking_functions.availability import check_availability

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
import environ

env = environ.Env(
# set casting, default value
DEBUG=(bool, True)
)

environ.Env.read_env()


# Create your views here.


def RoomListView(request):
    room = Room.objects.all()[0]
    room_categories = dict(room.ROOM_CATEGORIES)
    room_values = room_categories.values()
    room_list = []

    for room_category in room_categories:
        room = room_categories.get(room_category)
        room_url = reverse('hotel:RoomDetailView', kwargs={
                           'category': room_category})

        room_list.append((room, room_url))
    context = {
        "room_list": room_list,
    }
    return render(request, 'room_list_view.html', context)


class BookingListView(ListView):
    model = Booking
    template_name = "booking_list_view.html"

    def get_queryset(self, *args, **kwargs):
        if self.request.user.is_staff:
            booking_list = Booking.objects.all()
            return booking_list
        else:
            booking_list = Booking.objects.filter(user=self.request.user)
            return booking_list

    

class RoomDetailView(View):
    def get(self, request, *args, **kwargs):
        print(self.request.user)
        category = self.kwargs.get('category', None)
        form = AvailabilityForm()
        room_list = Room.objects.filter(category=category)

        if len(room_list) > 0:
            room = room_list[0]
            room_category = dict(room.ROOM_CATEGORIES).get(room.category, None)
            context = {
                'room_category': room_category,
                'form': form,
            }
            return render(request, 'room_detail_view.html', context)
        else:
            return HttpResponse('Category does not exist')

    def post(self, request, *args, **kwargs):
        category = self.kwargs.get('category', None)
        room_list = Room.objects.filter(category=category)
        form = AvailabilityForm(request.POST)

        if form.is_valid():
            data = form.cleaned_data

        available_rooms = []
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)

        if len(available_rooms) > 0:
            room = available_rooms[0]
            booking = Booking.objects.create(
                user=self.request.user,
                room=room,
                check_in=data['check_in'],
                check_out=data['check_out']
            )
            booking.save()
            return HttpResponseRedirect('booking_list/')
            # return HttpResponse(booking)
        else:
            return HttpResponse('All of this category of rooms are booked! Try another one')
    # success_url = reverse_lazy('hotel:BookingListView')


class CancelBookingView(DeleteView):
    model = Booking
    template_name = 'booking_cancel_view.html'
    success_url = reverse_lazy('hotel:BookingListView')

hotel/templates/booking_cancel_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1565031491910-e57fac031c41?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=700&q=60">
        
        </div>

        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{booking.get_room_category}} Suite</h1>
                <br/>
                <p>Guest will find this room both ideal for work and leisure.</p>
                <br/>
                <p>Room size- 21 m2</p>
                <p>Amenities - Private attached bathroom, in room services are available, internet and intercom facilities are also
                    available, front desk services are also available, color television is also available, it will be a memorable stay
                    for the guests and will enjoy the hospitality, guests will have a lavish and luxurious stay and will experience the
                    best stay in the hotel.</p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}
                <h3>Are you sure you wanna cancel this Booking? </h3>
                <br/>
                <p>{{booking.room.number}} {{booking.get_room_category}} {{booking}}</p>
                <br/>
                <!-- Input Div -->
                <div class="input-div">
                    <button type="submit">Cancel the Booking</button>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

hotel/templates/booking_list_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Booking List</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'hotel/css/booking_list_view.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
</head>

<body>
    <div class="content">
        <div class="header">
            <div class="headings">
                <h1>Your Bookings</h1>
                <h2>Welcome {{user}}!</h2>
            </div>
            <div class="home">
                <!-- Div 1: Back to Home -->
                <div class="home">
                    <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
                </div>
            </div>

        </div>

        <div class="bookings">
            {% for booking in booking_list %}
            <div class="booking">
                {% if booking.get_room_category == "AC" %}
                <img
                src="https://images.unsplash.com/photo-1508253578933-20b529302151?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjh8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
                />
                {% elif booking.get_room_category == "NON-AC" %}
                <img
                src="https://images.unsplash.com/photo-1595161695996-f746349f4945?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
                />
                {% elif booking.get_room_category == "KING" %}
                <img
                src= "https://images.unsplash.com/photo-1590490359854-dfba19688d70?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=1000&q=60"
                />
                {% elif booking.get_room_category == "QUEEN" %}
                <img
                src= "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8aG90ZWwlMjByb29tfGVufDB8fDB8&auto=format&fit=crop&w=700&q=60"
                />
                {% elif booking.get_room_category == "DELUXE" %}
                <img
                src="https://images.unsplash.com/photo-1576675762999-2d8ee979aac4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
                />
                {% endif %}
                <div class="category">
                    <h2>{{booking.get_room_category}} Suite</h2>
                </div>
                <div class="from">
                    <p>From: {{booking.check_in}}</p>
                </div>
                <div class="to">
                    <p>To: {{booking.check_out}}</p>
                </div>
                <div class="beds">
                    <p>Beds: {{booking.room.beds}}</p>
                </div>
                <div class="capacity">
                    <p>Capacity: {{booking.room.capacity}}</p>
                </div>
                <div class="cancel"><a href="{{booking.get_cancel_booking_url}}" class="invisible"><i
                            class="far fa-2x fa-times-circle"> Cancel
                            Booking</i></a></div>

            </div>
            {% endfor %}
        </div>
</body>

</html>

hotel/templates/room_detail_view.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Room Detail</title>
    <script src="https://kit.fontawesome.com/692189991f.js" crossorigin="anonymous"></script>

    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_detail_view.css' %}">

</head>

<body>

    <!-- Main Content -->
    <div class="content">

        <!-- Room Image -->
        <div class="image">
            <img
                src="https://images.unsplash.com/photo-1565031491910-e57fac031c41?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=700&q=60">
        
        </div>
        <!-- Room Details -->
        <div class="room">

            <!-- Div 1: Back to Home -->
            <div class="home">
                <a href="{% url 'hotel:RoomListView' %}"><i class="fas fa-arrow-alt-circle-left">Home</i></a>
            </div>

            <!-- Div 2: Room Information -->
            <div class="room-info">
                <h1>{{room_category}} Suite</h1>
                <br/>
                <p>Guest will find this room both ideal for work and leisure.</p>
                <br/>
                <p>Room size- 21 m2</p>
                <!-- <p>Ammenities - Wifi, TV</p> -->
                <p>Amenities - Private attached bathroom, in room services are available, internet and intercom facilities are also
                    available, front desk services are also available, color television is also available, it will be a memorable stay
                    for the guests and will enjoy the hospitality, guests will have a lavish and luxurious stay and will experience the
                    best stay in the hotel.</p>
            </div>

            <!-- Div 3: Room Booking Form -->
            <form id="booking-form" action="" method="POST">

                {% csrf_token %}

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_in">Check In : </label>
                    <input type="datetime-local" id="id_check_in" name="check_in">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <label for="id_check_out">Check Out : </label>
                    <input type="datetime-local" id="id_check_out" name="check_out">
                </div>

                <!-- Input Div -->
                <div class="input-div">
                    <a href="{% url 'hotel:BookingListView' %}"><button type="submit">Book the Room</button></a>
                </div>

            </form>

        </div> <!-- END Room Div -->

    </div> <!-- END Main Content Div -->

</body>

</html>

hotel/templates/room_list_view.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Parador</title>
    <!-- Main StyleSheet -->
    <link rel="stylesheet" href="{% static 'hotel/css/room_list_view.css' %}" />
    <link rel="stylesheet" href="{% static 'hotel/css/nav.css' %}" />
  </head>

  <body>
    <div class="container">
      <!-- Navbar -->
      <nav id="navbar">
        <div class="brand">
          <h1 id="logo">Parador</h1>
        </div>
        <div id="ham-div"  onclick="togglenav()">
            <img id="ham" src="https://img.icons8.com/material-rounded/24/000000/menu.png"/>
        </div>
        <div id="navlist-div" class="">
          <ul id="navlist" class="folding-nav hidden">
            {% if request.user.is_authenticated %}
            <li><a href="{% url 'hotel:BookingListView' %}">My Bookings</a></li>
            <li><a href="{% url 'account_logout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account_login' %}">Login</a></li>
            <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>

      <!-- Landing -->
      <div class="landing">
        <h1>Luxury <span>Re-Defined</span></h1>
        <img
          src="https://images.unsplash.com/photo-1444201983204-c43cbd584d93?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTN8fGhvdGVsfGVufDB8fDB8&auto=format&fit=crop&w=500&q=60"
          id="landing-img"
          alt="Best Hotel in the World"
          srcset=""
        />
      </div>

      <h2>Rooms</h2>
      <!-- Main Content -->
      <div id="rooms">
        {% for room_category, room_url in room_list %}
        <div class="room">
          <a href="{{room_url}}">
          {% if room_category == "AC" %}
            <img
            src="https://images.unsplash.com/photo-1508253578933-20b529302151?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mjh8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
            />
            <h2>{{room_category}} Suite<h2>
            <p>
              The Deluxe AC Room is the comfortable choice for two occupants. The rooms are equipped with television wooden closet, comfortable bed and center table.
            </p>
          {% elif room_category == "NON-AC" %}
          <img
          src="https://images.unsplash.com/photo-1595161695996-f746349f4945?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjF8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
          />
          <h2>{{room_category}} Suite<h2>
          <p>
            Standard Non AC rooms are well decorated and fully furnished rooms, it has all the basic amenities 
            <!-- like private attached
            bathroom, in room services are available, internet and intercom facilities are also available, front desk services are
            also available, color television is also available, it will be a memorable stay for the guests and will enjoy the
            hospitality, guests will have a lavish and luxurious stay and will experience the best stay in the hotel. -->
          </p>
          {% elif room_category == "KING" %}
            <img
            src= "https://images.unsplash.com/photo-1590490359854-dfba19688d70?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjR8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=1000&q=60"
            />
            <h2>{{room_category}} Suite<h2>
            <p>
              Our king size room has a seating area, ample storage, digital safe, minibar and luxurious duck down bedding
            </p>
          {% elif room_category == "QUEEN" %}
          <img
          src= "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8NHx8aG90ZWwlMjByb29tfGVufDB8fDB8&auto=format&fit=crop&w=700&q=60"
          />
          <h2>{{room_category}} Suite<h2>
          <p>
            Standard Queen rooms are medium sized rooms and offer a queen sized bed, en suite shower over
            bath and WC, free and secure wireless internet. 
          </p>
          {% elif room_category == "DELUXE" %}
            <img
            src="https://images.unsplash.com/photo-1576675762999-2d8ee979aac4?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdGVsJTIwcm9vbXxlbnwwfHwwfA%3D%3D&auto=format&fit=crop&w=500&q=60"
            />
            <h2>{{room_category}} Suite<h2>
          <p>
            Our Deluxe king size room has a seating area, ample storage, digital safe, minibar and luxurious duck down bedding
          </p>
          {% endif %}
          
          
          </a>
        </div>

        {% endfor %}
      </div>
    </div>
    <script src="{% static 'hotel/js/nav.js' %}"></script>
  </body>
</html>